### ISSUE TITLE
ShellItemRenderer.java - Error when building Android Solution

### ISSUE THREAD

**Issue by kerberosargos** [xamarin/Xamarin.Forms#14492]
Hello after update **Xamarin.Android bindings for AndroidX** package from 1.3.0.1 to 1.4.0 it gives error as following in build Android Solution time. There is no problem in version 1.3.0.1

```
Error error: ShellItemRenderer is not abstract and does not override abstract method onNavigationItemSelected(MenuItem) in OnItemSelectedListener
public class ShellItemRenderer My.Android c:\ShellItemRenderer.java 4

Error error: TabbedPageRenderer is not abstract and does not override abstract method onNavigationItemSelected(MenuItem) in OnItemSelectedListener
public class TabbedPageRenderer My.Android C:\TabbedPageRenderer.java 4 
```

**Comment by paulocarinhena** [comment]
Me too.

**Comment by MagicAndre1981** [comment]
> Me too.

you need to wait until #14506 is merged and SR5 is out

**Comment by zipgenius** [comment]
This is still an issue in v. 1.4.0.2
The only workaround is to downgrade to 1.3.0.1

**Comment by MagicAndre1981** [comment]
> This is still an issue in v. 1.4.0.2
> The only workaround is to downgrade to 1.3.0.1

read my comment below, you need to wait until the mentioned RP is merged into XF and SR5 gets released.

**Comment by kissurda** [comment]
Hi,

5.0.0.2125 update is works for me.

Thx

**Comment by IoTFier** [comment]
> Hi,
> 
> 5.0.0.2125 update is works for me.
> 
> Thx

Ditto.

**Comment by jfversluis** [comment]
Looks like this is resolved now, thanks!

**Comment by alexmartinezm** [comment]
Can you please ping me when this is fixed on Xamarin.Forms 5.0.0.2244? Thanks...

**Comment by Codelisk** [comment]
Still not fixed

**Comment by ClumsyPenguin** [comment]
Updating Xamarin.Forms to `5.0.0.2401` and then explicitly updated both Xamarin.Android to `1.7.0.2` and Xamarin.Google.Android.Material `1.5.0.2` fixed it for me

**Comment by suchithm** [comment]
> Updating Xamarin.Forms to `5.0.0.2401` and then explicitly updated both Xamarin.Android to `1.7.0.2` and Xamarin.Google.Android.Material `1.5.0.2` fixed it for me

Fixed with this particular versions
