### ISSUE TITLE
[iOS] MasterDetailPage - SplitView and SlideOver: Detail Controller missing

### ISSUE THREAD

**Issue by themultiplexer** [xamarin/Xamarin.Forms#3085]
### Description
With the latest Version (3.0.0.**561731**) the SlideOver- and SplitView-Feature of iOS on iPads are broken: Only the Master is shown. 

Version 3.0.0.**446417** and 3.0.0.**482510** were working flawlessly.
Additional Info: If the _MasterBehavior_ was not set the menu was hidden in landscape by default (not split in landscape) and the _Master_ was way more wide than usual (but better than Popover IMHO).

### Steps to Reproduce
1. Clone Repro Project
2. Install Xamarin.Forms between 3.0.0.**530893** and 3.0.0.**561731**
2. Run on iPad Air 2 or iPad (5th Generation)
3. Go in to any other App and drag the _MasterDetailBugReproductionApp_ into the current App

### Expected Behavior
The App is simply smaller and behaves like on a iPhone.

### Actual Behavior
The whole Detail Controller is missing.

### Basic Information
- Version with issue: 3.0.0.**530893** until 3.0.0.**561731**
- Last known good version: 3.0.0.**482510**
- IDE: Visual Studio 15.7.3
- Platform Target Frameworks:
  - iOS:  11.4
- Affected Devices:
 - iPad

### Similar Issues
#2017 

### Screenshots
<details> 
  <summary>Expected</summary>
<img title="SlideOver" src="https://user-images.githubusercontent.com/22082747/41602704-bcc924a8-73db-11e8-9cdc-57b1a3ca87f5.png" width="40%"/>
<img title="SplitView" src="https://user-images.githubusercontent.com/22082747/41603072-841d75ae-73dc-11e8-874b-b6f2b366ce6e.png" width="40%"/>
</details>

<details> 
  <summary>Actual</summary>
<img title="SlideOver" src="https://user-images.githubusercontent.com/22082747/41603187-c5464b32-73dc-11e8-87fc-ea78abf3ef42.png" width="40%"/>
<img title="SplitView" src="https://user-images.githubusercontent.com/22082747/41603223-d38d3fca-73dc-11e8-96fc-a7b7f1bd1fb6.png" width="40%"/>
</details>

### Reproduction Link
https://github.com/themultiplexer/MasterDetailBugReproduction

**Comment by kingces95** [comment]
Behavior is as described on latest nightly. 

Fyi, trying to run on master observed the following build errors: 
> C:\Users\Chris\Downloads\3085\MasterDetailBugReproduction-master\MasterDetailBugReproduction\MasterDetailBugReproduction.iOS\AppDelegate.cs(14,62,14,70): error CS0234: The type or namespace name 'Platform' does not exist in the namespace 'Xamarin.Forms' (are you missing an assembly reference?)
> C:\Users\Chris\Downloads\3085\MasterDetailBugReproduction-master\MasterDetailBugReproduction\MasterDetailBugReproduction.iOS\AppDelegate.cs(23,30,23,47): error CS0115: 'AppDelegate.FinishedLaunching(UIApplication, NSDictionary)': no suitable method found to override

**Comment by kingces95** [comment]
Bisected regression to https://github.com/xamarin/Xamarin.Forms/commit/5fdec77627914e30f9f2c4e05011c244ddf53b52

**Comment by themultiplexer** [comment]
When will this be fixed? 3.3.0 or later?

**Comment by samhouts** [comment]
Our current schedule shows this work beginning in April, but I will mark it with `help-wanted` to see if the community can help out sooner than that. Thank you for your patience!

**Comment by sylendra7** [comment]
@samhouts  Hi, when this feature will come or when this issue will fix...?

**Comment by Sebastian1989101** [comment]
@samhouts will this work also fix #2017? Because this issue is present since 2015 and was still not addressed..

**Comment by SebastianKruseWago** [comment]
@samhouts Any update on this and #2017? It still limits the capability of iOS apps on iPads a lot.

**Comment by Sebastian1989101** [comment]
@samhouts Is there any update on this yet? It's May already and it would be time for a fix after so many years leaving this bugged...

**Comment by Sebastian1989101** [comment]
This is how the MasterDetail of the Control Gallery looks like on an iPad when splitting 50:50 and then again 75:25. I think this issue is caused by this fix (which may also the reason for the SplitView Bug in the first place then?): https://github.com/xamarin/Xamarin.Forms/commit/689a0bb9bc14b0beecb7bdf96315c28e0166cff7#diff-79b77d2f40e6a52dd3b2724e0178814e 

![Simulator Screen Shot - iPad Pro (11-inch) - 2019-06-04 at 21 49 26](https://user-images.githubusercontent.com/25636075/58909149-a8a41f00-8712-11e9-9fe7-eb0fdff0e9a1.png)

I'm currently testing a few things so maybe I can make a PR for this (at least if I can find a solution that works - I'm not very experienced with the native stuff yet).

**Comment by PureWeen** [comment]
duplicate of https://github.com/xamarin/Xamarin.Forms/issues/2017

**Comment by boris-df** [comment]
I have the same problem. Xamarin.Forms 4.6
Problem on an iPad if i put my App Side-by-side with some other App (for example Safari left, My App right):
- Split both Apps to 25/75 = My App shows just fine; Burger-Menü to show Master (PopOver) 
- Split Apps to 50/50 or 75/50 = My App only shows the Menu! Detail View is never visible

I tried a CustomRenderer like this but it didn't really help. I Played with the parameter but whenever i manage to get the detail to show, the Burger-Menü-Item is gone (the Navigation Back Button gone too) and as soon as i use some other parameters to see the Navigation again, the Detail-View is lost again (is the App is side by side with 50% or 25%)

here is the custom-renderer with that i played
`[assembly: ExportRenderer(typeof(MasterDetailPage), typeof(MyMasterDetailPageRenderer), UIUserInterfaceIdiom.Pad)]


/// <summary>
/// Eigener Renderer für Xamarin.Forms NavigationPage
/// Warum? 
///   
/// Quellen:
/// https://forums.xamarin.com/discussion/171025/ios-13-ipados-13-master-detail-page-always-visible-on-ipad-in-landscape-mode
/// https://forums.xamarin.com/discussion/96359/using-ios-9-multitasking-splitview-with-a-masterdetail-page
/// 
/// </summary>
namespace DATAflor.Team.iOS.Renderer
{
    public class MyMasterDetailPageRenderer : TabletMasterDetailRenderer
    {
        NavigationPage NavPage => Element as NavigationPage;

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
           // this.PreferredDisplayMode = UISplitViewControllerDisplayMode.PrimaryOverlay;
        }

        protected override void OnElementChanged(VisualElementChangedEventArgs e)
        {
            base.OnElementChanged(e);

            PreferredDisplayMode = UISplitViewControllerDisplayMode.PrimaryOverlay;
        }

        public override void WillRotate(UIInterfaceOrientation toInterfaceOrientation, double duration)
        {
            base.WillRotate(toInterfaceOrientation, duration);

            PreferredDisplayMode = UISplitViewControllerDisplayMode.PrimaryOverlay;
        }

        public override UITraitCollection TraitCollection => UITraitCollection.FromHorizontalSizeClass(UIUserInterfaceSizeClass.Regular); //Regular
    }
}`

Any solution out there? (besides of completly rewriting the app without MasterDetail and coding some own Menu-Overlay-Bahaviour?

**Comment by Sebastian1989101** [comment]
@boris-df No, there is no solution except coding it yourself or simply disable SplitView by require Fullscreen all the time. Thiss issue is here since 2017 and Xamarin does not care about it. Only thing you can try is replacing the whole Xamarin.Forms renderer for iPad MasterDetail but you will have to adjust it to every change from Xamarin than.

**Comment by boris-df** [comment]
@Sebastian1989101 wow that is sad! Yes i found threads about this back to 2015. Different workarounds thru the time with different Xamarin and iOS Versions  - but currently there doesn't seem to be working solution for XF 4.6 + iOS13

Even with completly copying the Renderer i would not know where to fix this (i think if it would be that simple, it would be fixed already?)

Oh boy... i have a menu as Master... is there good practice to "fake" such a Pop/swipe-Over-Menu with simple NavigationPage/Page Pattern that works with Xamarin.Forms on Android and iOS (Meaning: Burger-Menu-Icon if you are at the root level; Swipe from left-to-right to open it animated with Pan gesture or something)?
