### ISSUE TITLE
Compilation error after upgrade from 2.5.1.527436 to 3.0.0.446417

### ISSUE THREAD

**Issue by Nukepayload2** [xamarin/Xamarin.Forms#2648]
### Description
My project is unable to build normally after upgrade the Xamarin.Forms package from 2.5.1.527436 to 3.0.0.446417.

### Steps to Reproduce
1. Clone my codes from https://github.com/Nukepayload2/Nukepayload2.UI.XamarinForms.git
2. Open "Nukepayload2.UI.XamarinForms.sln" with Visual Studio 2017.
3. Right click on project "Nukepayload2.UI.XamarinForms", and click "Build".
4. Build should success if you have configured your build environment correctly.
5. Upgrade nuget package "Xamarin.Forms"
6. Close the solution.
7. Remove bin and obj folders manually.
8. Reopen the solution.
9. Right click on project "Nukepayload2.UI.XamarinForms", and click "Build".

### Expected Behavior
Build succeed.

### Actual Behavior
Build failed with errors:
1>------ 已启动生成: 项目: Nukepayload2.UI.XamarinForms, 配置: Debug Any CPU ------
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Themes\ChatViewTemples.xaml : error : 值不能为 null。
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Themes\ChatViewTemples.xaml : error : 参数名: value
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Themes\DefaultContentTemplates.xaml : error : 值不能为 null。
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Themes\DefaultContentTemplates.xaml : error : 参数名: value
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Themes\TimelineTemplates.xaml : error : 值不能为 null。
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Themes\TimelineTemplates.xaml : error : 参数名: value
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\ChatView.xaml : error : 值不能为 null。
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\ChatView.xaml : error : 参数名: value
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\CheckBox.xaml : error : 值不能为 null。
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\CheckBox.xaml : error : 参数名: value
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\ComboBox.xaml : error : 值不能为 null。
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\ComboBox.xaml : error : 参数名: value
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\EditorControl.xaml : error : 值不能为 null。
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\EditorControl.xaml : error : 参数名: value
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\EmbeddedWebViewPage.xaml : error : 值不能为 null。
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\EmbeddedWebViewPage.xaml : error : 参数名: value
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\Expander.xaml : error : 值不能为 null。
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\Expander.xaml : error : 参数名: value
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\Flyout.xaml : error : 值不能为 null。
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\Flyout.xaml : error : 参数名: value
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\FlyoutContainer.xaml : error : 值不能为 null。
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\FlyoutContainer.xaml : error : 参数名: value
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\HyperlinkButton.xaml : error : 值不能为 null。
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\HyperlinkButton.xaml : error : 参数名: value
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\TimelineEditor.xaml : error : 值不能为 null。
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\TimelineEditor.xaml : error : 参数名: value
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\TimelineView.xaml : error : 值不能为 null。
1>G:\vs2017\Nukepayload2.UI.XamarinForms\Nukepayload2.UI.XamarinForms\Views\TimelineView.xaml : error : 参数名: value

### Basic Information
- Version with issue: 3.0.0.446417
- Last known good version: 2.5.1.527436
- IDE: Microsoft Visual Studio 2017 15.7.1 (locale: zh-CN)
- Platform Target Frameworks:
  - iOS: Not installed
  - Android: 8.0
  - UWP:  17134
- Android Support Library Version: 27.0.2
- Nuget Packages: xamarin.forms
- Affected Devices: all

*NOTE*: PLEASE DON'T tell me that this bug will NOT be fixed or it is not a bug because I am using Visual Basic, because my customers insist that my control library should use VB only. If you really don't want to fix it, please tell me how to fix it without changing my code. Then I'll crush this bug and test by myself and create a pull request to this repo.

**Comment by socialbodega** [comment]
After upgrading to 3.0, I started getting this "linker command failed with exit code 1" for solution with PCL project referenced to native projects. Any clues?

**Comment by StephaneDelcroix** [comment]
@S1r-Lanzelot are you using VB as well ?

**Comment by S1r-Lanzelot** [comment]
@StephaneDelcroix no c#

**Comment by StephaneDelcroix** [comment]
@S1r-Lanzelot not sure the issue is related, please open a new ticket, with an attached project

**Comment by StephaneDelcroix** [comment]
> NOTE: PLEASE DON'T tell me that this [...] is not a bug

This is not a bug

> NOTE: PLEASE DON'T tell me that this bug will NOT be fixed

This won't be fixed, as it's not a bug.

What's happening ? your `GeneratedForXaml.tt` script is a good attempt to port `XamlG` to generate `VB`. In `3.0.0`, the `XamlG` script was modified to generate `XamlResourceIdAttribute` (https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Xaml/XamlResourceIdAttribute.cs). Later on, `XamlC` depends on them being presents, but fails in your case.

by adding that attribute to one of your view, I was able to make the error for that view disappear.

**Comment by Nukepayload2** [comment]
@StephaneDelcroix Thanks for your advice.
I wrote the meaningless "note" section because I was too anxious at that day. I'm sorry if that part makes you feel confused.
