### ISSUE TITLE
TabbedPageRenderer.java - Error when building Android Solution

### ISSUE THREAD

**Issue by jonathanantoine** [xamarin/Xamarin.Forms#14692]
### Description
Hello after update Xamarin.Android bindings for AndroidX package from 1.3.0.1 to 1.4.0 it gives error as following in build Android Solution time. There is no problem in version 1.3.0.1

``` 
TabbedPageRenderer is not abstract and does not override abstract method onNavigationItemReselected(MenuItem) in OnItemReselectedListener
public class TabbedPageRenderer
 (JAVAC0000) 
```
### Steps to Reproduce
```xml
<PackageReference Include="Xamarin.Forms" Version="5.0.0.2125" />
<PackageReference Include="Xamarin.Google.Android.Material" Version="1.4.0.0" />
```
### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by MagicAndre1981** [comment]
latest version is 1.4.0.4, try this one:

`<PackageReference Include="Xamarin.Google.Android.Material" Version="1.4.0.4" />`

**Comment by jfversluis** [comment]
Could you confirm with updating all the dependencies to the newest version and on your filesystem delete all the bin and obj folders from each of the project folders (so shared, Droid, iOS, etc.) and then rebuilding. Does the problem then still show?

If so, would you be able to provide us with a small reproduction project that shows this issue?

**Comment by jonathanantoine** [comment]
@jfversluis the problem is still here after this procedure. 
If I took the time to do it, will you try to fix the issue ?

**Comment by jfversluis** [comment]
That's what I'm here for!

**Comment by MichaelRumpler** [comment]
I also tried to update XF from 5.0.0.2083 to 2125 and got these errors:

	10>D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ShellItemRenderer.cs(27): error XA4204: Unable to resolve interface type 'Google.Android.Material.Navigation.NavigationBarView/IOnItemSelectedListener'. Are you missing an assembly reference?
	10>D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\TabbedPageRenderer.cs(50): error XA4204: Unable to resolve interface type 'Google.Android.Material.Navigation.NavigationBarView/IOnItemSelectedListener'. Are you missing an assembly reference?

But then I tried again with deleting all bin and obj folders and then it worked. So apparently the update leaves some old dlls behind again. I'm now on the latest versions of XF and all AndroidX components.

**Comment by jonathanantoine** [comment]
Thank you @jfversluis
