### ISSUE TITLE
Linker Error with macOS 10.12 and Xamarin Forms for macOS

### ISSUE THREAD

**Issue by jcapellman** [xamarin/Xamarin.Forms#2651]
### Description
Receiving the following build error on 10.12 with the latest Stable VS for Mac:

"/Library/Frameworks/Xamarin.Mac.framework/Versions/4.4.1.176/src/Xamarin.Mac/BusinessChat/BCChatButton.g.cs(0,0): Error MM4162: The type 'BusinessChat.BCChatButtonStyle' (used as a parameter in BusinessChat.BCChatButton..ctor) is not available in macOS 10.13.2 (it was introduced in macOS 10.13.4). Please build with a newer macOS SDK (usually done by using the most recent version of Xcode). (MM4162) (OurApp.Xamarin.macOS)"

### Steps to Reproduce

1. Create a new Xamarin Forms App on macOS on macOS 10.12 with VS for Mac 7.5
2.  Attempt to build and receive the stack trace above

### Expected Behavior
The app builds and runs as it had before the latest Stable Update

### Actual Behavior
Stack Trace above

### Basic Information
-VS for Mac 7.5 (Stable Channel)
-macOS 10.12 (fully up to date other than not being on 10.13)

**Comment by jcapellman** [comment]
A workaround to keep my team going was to set the "Link Platform" on Linker Behavior for our Release Builds.

**Comment by socialbodega** [comment]
After upgrading to 3.0, I started getting this "linker command failed with exit code 1" for solution with PCL project referenced to native projects. Any clues?

**Comment by StephaneDelcroix** [comment]
could you give a look at this, @rmarinho ?

**Comment by chamons** [comment]
`Please build with a newer macOS SDK (usually done by using the most recent version of Xcode). (MM4162) (OurApp.Xamarin.macOS)"` - You have to enable linking (platform, sdk, or all), downgrade your XM, or upgrade your XCode.

**Comment by jcapellman** [comment]
@chamons 
Thanks for getting back to me.  Figured those would be the options.   Fortunately, 10.13 works fine with the latest XCode, though the rest of my macOS dev team is on 10.12 due to the display link issues.

**Comment by samhouts** [comment]
Is this issue resolved? Thanks!

**Comment by jcapellman** [comment]
I wouldn't say its resolved, but there is a work around simply by updating.  If it weren't for the Apple Display Link issues it would be a non issue in my case.

**Comment by samhouts** [comment]
Understood. We'll go ahead and close this issue, since there isn't much we can do at this time, but let us know if we can be of further help. Thank you!
