### ISSUE TITLE
Xamarin XAML Compilation: Bad Property Values Should Be Identified by Line

### ISSUE THREAD

**Issue by StephaneDelcroix** [xamarin/Xamarin.Forms#4099]
### Description

[from [https://developercommunity.visualstudio.com/idea/357990/xamarin-xaml-compilation-bad-property-values-shoul.html](https://developercommunity.visualstudio.com/idea/357990/xamarin-xaml-compilation-bad-property-values-shoul.html)]

In Xamarin XAML, and this was confirmed as last as v3.2, if you have a property with a bad value, a compilation error displays in the error list after build:

"Exception has been thrown by the target of an invocation", with a source of Filename.xaml, where Filename is whichever XAML file the error occurred.

Instead of what seems like a cryptic error, please explain which on which line of the XAML the error was found.

To reproduce:

Create XAML and in a StackLayout element, add a Padding of "2 2 2 5". The value should be "2,2,2,5", but the point is to have the spaces. The compilation error will appear and you'll see what I mean. If you've been working on XAML for an hour or two, and you make a - maybe rookie :) - mistake, finding out exactly where the compiler is having trouble is a nightmare. I imagine there's more helpful information available when you compile, so if you could surface that at the very least please, that would be great. Ideally, the Line number or even the element/property would be fantastic.

Thanks!

-Auri, Certified Xamarin Mobile Developer

**Comment by StephaneDelcroix** [comment]
oh, this is a good one... the right exception is actually thrown, but embedded as inner exception:

> System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> Xamarin.Forms.Xaml.XamlParseException : Position 5:15. Cannot convert "2 2 2 5" into Xamarin.Forms.Thickness
```
