### ISSUE TITLE
Cannot automate Label clicking after XF 2.5.0 update

### ISSUE THREAD

**Issue by jsbakker** [xamarin/Xamarin.Forms#1589]
### Description

Unable to click on certain Labels via automation after updating a UWP app to latest Xamarin.Forms.

While Labels aren't usually directly "clickable", sometimes it's necessary to create compound controls which include Labels, such as in custom "buttons" or list items, when the stock XF Button or TextCell isn't sufficient. The Labels in question have parent view that is clickable either by nature (List item) or by TapGestureRecognizer, if it is a StackLayout.

Basic example 1: you want a button with configurable image positioning relative to the button text, or to be able to set text alignment of the button. Stock XF button cannot do this, so you throw an Image and Label inside of a StackLayout and put a TapGestureRecognizer on it. Whether the tap recognizer is on the parent or on the Label itself, neither are clickable in automation anymore.

Basic example 2: your listview item image sources are coming from outside the app and may have inconsistent sizes, and you want to fix the image size or use another library to cache the images. ImageCell cannot do this, so you use ViewCell with an Image and Label inside of a StackLayout.

This issue is not affecting Android; it only appears on UWP. Also, the issue appeared only after upgrading from Xamarin.Forms 2.3.2.127 => 2.5.0.122203. Reverting back to 2.3.2.127 confirmed this. Since working automation started failing after the XF update, this is assumed to be a Xamarin.Forms behavior change, not a bug in the Automation framework.

### Steps to Reproduce

1. Find the element representing the Label (Selenium Ruby example below)
> `label = driver.find_elements(:name, "LabelName")`
2. The above returns an array with 1 element. Now, click on the element
> `label[0].click()`

### Expected Behavior
The clickable item containing the Label will respond to the click request on the label.

### Actual Behavior
> `label[0].click()`

```NoMethodError: undefined method `[]' for nil:NilClass
from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:82:in `add_backtrace'```

### Basic Information

- Version with issue: 2.5.0.122203
- Last known good version: 2.4.0.280
- IDE: Visual Studio 2015 Update 3
- Platform Target Frameworks:
  - Android: 7.1
  - UWP:  14393
- Affected Devices: Windows Desktop
- Automation used for UWP: Selenium via WinAppDriver (https://github.com/Microsoft/WinAppDriver)
- Automation used for Android: Calabash

### Reproduction Link
I have reproduced expected working functionality with XF 2.4.0.280 in a standalone app. After updating to 2.5.0 the error is reproduced. See Readme.md in the zip file for reproduction setup.

[LabelClickable.zip](https://github.com/xamarin/Xamarin.Forms/files/1633244/LabelClickable.zip)

**Comment by jsbakker** [comment]
This does not occur with 100% of the labels in my application, but for the labels it does occur on, it is 100% reproducible. There are multiple areas where a label is inside of a parent that is clickable, and here are different examples of view hierarchy using labels.

1. Label inside v. stacklayout sublcass
2. Label inside h. stacklayout, inside itemtemplate (non-ListView)
3. Label inside h. stacklayout subclass, inside itemtemplate (non-ListView)
4. Label inside stacklayout inside ViewCell in ListView itemtemplate

2.3.2
- Label 1 : findable, clickable
- Label 2 : findable, clickable
- Label 3 : findable, clickable
- Label 4 : findable, clickable

2.5.0
- Label 1 : findable, throw on click*
- Label 2 : findable, clickable
- Label 3 : findable, throw on click*
- Label 4 : found with automationproperty.name, throw on click*
- Change Label 4. to Label inside ViewCell in ListView itemtemplate : throw on click*
- Change Lable 4. to a regular ImageCell or TextCell : findable, clickable

_*Selenium is throwing on click, not the application_

The sample reproduction app has the simplest case to 100% reproduce the issue.

**Comment by jsbakker** [comment]
So I have found the main difference in my application between labels which can be clicked and labels which cannot be clicked by Selenium/WinAppDriver.

1. If the Label's property InputTansparent = true and its parent layout is clickable, then Selenium can click on it and it will work as expected.
2. If the Label's property InputTransparent is not set (false by default) and its parent layout is clickable, then Selenium will throw an error back when attempting to click on it.

Logically that makes sense for the child element to not catch input for its container, which handles the click. However, when the Label itself has a TapGestureRecognizer on it, the opposite is expected; you should not have to set input transparent to be able to tap on it because you want the label, and not the parent, to catch the click.

**Comment by rmarinho** [comment]
Hi @jsbakker can you try the latest versions 3.1.0-pre4 see if helps with your issues? 

@samhouts after we removing our automationid on uwp would we have made this better or worse? 

Thanks

**Comment by samhouts** [comment]
We may have made it worse with #2876. @PureWeen, any thoughts on this?

**Comment by jsbakker** [comment]
@rmarinho I have limited availability for verifying this right now; I have a new employer, am no longer in UWP development and I don't own a copy of Windows at home. I will see what I can do by the end of this week.

Otherwise, the .zip I attached contains a 100% reproducible VS solution and a readme.md explaining all the required setup and commands in detail for reproducing the issue.

**Comment by PureWeen** [comment]
I didn't run with the ruby version of these but instead added a selenium project

With 2.5.1 I get this exception
```
Message: Test method LabelClickable.Selenium.LabelClickableTest.ClickMe threw exception: 
System.InvalidOperationException: An unknown error occurred in the remote end while processing the command.
```

With 3.1 pre 4 it clicked the button and passed and with our latest internal 3.1 build it also clicked the element and passed

Here's my project using a non ruby testing thing
[LabelClickable.zip](https://github.com/xamarin/Xamarin.Forms/files/2120819/LabelClickable.zip)

@samhouts   so I would take that to mean 3.1 will make this better?

**Comment by samhouts** [comment]
That looks very promising! Nice work @PureWeen! I think we can go ahead and close this issue as resolved. @jsbakker (or anyone else with a similar issue): if you find that the issue is not resolved, please feel free to reopen it! Thanks, everyone!

**Comment by jsbakker** [comment]
Thanks @PureWeen !
