### ISSUE TITLE
MultiTarget Error with different versions of Xamarin.Forms

### ISSUE THREAD

**Issue by YZahringer** [xamarin/Xamarin.Forms#2843]
### Description
I am trying to create a multitarget project .NETStandard 1.4 and .NETStandard 2.0 that use two different versions of Xamarin.Forms (2.x & 3.x).

This would be useful for creating a compatible library with .NETStandard 1.4 and UWP 10.0.10240 (which is not compatible with .NETStandard 2.0).

### Steps to Reproduce

1. Create multitarget project `netstandard1.4;netstandard2.0`
2. Add Xamarin.Forms 3.x PackageReference in `netstandard2.0`
3. Add Xamarin.Forms 2.x PackageReference in `netstandard1.4`
4. Build project

### Expected Behavior
Build success

### Actual Behavior
Compilation error `XF002 Xamarin.Forms tasks do not match targets. Please ensure that all projects reference the same version of Xamarin.Forms, and if the error persists, please restart the IDE.`

### Basic Information
- Version with issue: 2.5.1.527436 & 3.0.0.482510
- IDE: Visual Studio Enterprise 15.7.2

### Reproduction Link
https://github.com/MADSENSE/Madsense.XamarinForms.Sample/tree/MultiTargeting

**Comment by YZahringer** [comment]
The error persists even with two projects that use two different versions of Xamarin.Forms in the same solution. All projects in the solution must use the same version of Xamarin.Forms, otherwise there is a compilation error.

So to create a compatible .NETStandard 1.4 and .NETStandard 2.0 library, you need to create two different solutions with different projects. Not the most practical solution...

**Comment by jassmith** [comment]
You cannot use two different versions of Xamarin.Forms in the same solution. Xamarin.Forms 3.0 ships with NetStandard 1.0 dlls.

**Comment by YZahringer** [comment]
I did not see compatibility with NETStandard 1.0 [https://github.com/xamarin/Xamarin.Forms/pull/1649](https://github.com/xamarin/Xamarin.Forms/pull/1649). Thank you.

But that does not work with UWP 10.0.10240: [https://github.com/xamarin/Xamarin.Forms/issues/2859](https://github.com/xamarin/Xamarin.Forms/issues/2859). It requires NETStandard 2.0.
