### ISSUE TITLE
XAMLG Compile Error upon upgrading to 3.1.0

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#3206]
### Description
App compiles and runs with latest 3.0, but fails to compile with 3.1.0. Error is:

```
/work/ConferenceVision/ConferenceVision/ConferenceVision/obj/Debug/netstandard2.0/Views/ImageDetailView.xaml.g.cs(51,51): Error CS0542: 'ImageDetailView': member names cannot be the same as their enclosing type (CS0542) (ConferenceVision)
```

### Steps to Reproduce

1. Clone and run ConferenceVision (link below)
2. Stop and update to 3.1.0. Clean. Obliterate. Close and Reopen the project.
3. Run and observe the error.

### Expected Behavior
Should not error.

### Actual Behavior
Boom,  error.

### Basic Information

- Version with issue: 3.1.0.583944
- Last known good version: 3.0.0.446417

- IDE: VS Mac 7.6
https://gist.github.com/davidortinau/d7478115f92c1b44871b237896106430

### Reproduction Link
https://github.com/Microsoft/ConferenceVision

**Comment by davidortinau** [comment]
Ok I see this was introduced in #2582. My issue is/was the `x:Name` here:

```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core" 
             ios:Page.UseSafeArea="false"
             x:Name="ImageDetailView"
```
