### ISSUE TITLE
[Bug] NoSuchMethodError: no static method FormsViewGroup.sendViewBatchUpdate after updating VS to 8.5

### ISSUE THREAD

**Issue by baruchn** [xamarin/Xamarin.Forms#10094]
### Description
Updated Visual Studio Community and several NuGet packages in a working solution. Now when trying to run on an Android device or simulator getting the following error:

> Java.Lang.NoSuchMethodError: no static method "Lcom/xamarin/forms/platform/android/FormsViewGroup;.sendViewBatchUpdate(Landroid/view/View;FFIZFFFFFFFF)V"

Tried clean all and delete bin/obj as described in [this](#3981) issue but didn't help.

### Steps to Reproduce

Update from VS 8.4 and Forms 4.3 to VS 8.5 and Forms 4.5. Also updated all NuGet packages to the latest versions. See the details below.

### Expected Behavior

The application should run.

### Actual Behavior

The application crashes upon start.

### Basic Information

- Version with issue: 4.5.0.495
- Last known good version: 4.3 (VS 8.4)
- IDE: Visual Studio Community: 8.5 (build 3183)
- Platform Target Frameworks: 
  - Android: Android 10 (API 29)
- Android Support Library Version: 29.0.3
- Nuget Packages:
![Screen Shot 2020-03-26 at 10 31 27](https://user-images.githubusercontent.com/20625205/77626112-82739800-6f4d-11ea-83b5-a2661d0b0d13.png)
- Affected Devices: Pixel 2, Simulator of Pixel 3. Both running Android 10.

### Full Error:

Java.Lang.NoSuchMethodError: no static method "Lcom/xamarin/forms/platform/android/FormsViewGroup;.sendViewBatchUpdate(Landroid/view/View;FFIZFFFFFFFF)V"
  at Java.Interop.JniEnvironment+StaticMethods.GetStaticMethodID (Java.Interop.JniObjectReference type, System.String name, System.String signature) [0x0005b] in <26521a5118b44c858c385715922b9d5d>:0
  at Java.Interop.JniType.GetStaticMethod (System.String name, System.String signature) [0x0000c] in <26521a5118b44c858c385715922b9d5d>:0
  at Java.Interop.JniPeerMembers+JniStaticMethods.GetMethodInfo (System.String encodedMember) [0x00036] in <26521a5118b44c858c385715922b9d5d>:0
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeVoidMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00000] in <26521a5118b44c858c385715922b9d5d>:0
  at Xamarin.Forms.Platform.Android.FormsViewGroup.SendViewBatchUpdate (Android.Views.View p0, System.Single p1, System.Single p2, System.Int32 p3, System.Boolean p4, System.Single p5, System.Single p6, System.Single p7, System.Single p8, System.Single p9, System.Single p10, System.Single p11, System.Single p12) [0x0013a] in D:\a\1\s\Xamarin.Forms.Platform.Android.FormsViewGroup\obj\Release\generated\src\Xamarin.Forms.Platform.Android.FormsViewGroup.cs:279
  at Xamarin.Forms.Platform.Android.VisualElementTracker.UpdateNativeView (System.Object sender, System.EventArgs e) [0x000e4] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:313
  at Xamarin.Forms.Platform.Android.VisualElementTracker.HandleViewAttachedToWindow () [0x00008] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:188
  at Xamarin.Forms.Platform.Android.VisualElementTracker+AttachTracker.OnViewAttachedToWindow (Android.Views.View attachedView) [0x00013] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:407
  at Android.Views.View+IOnAttachStateChangeListenerInvoker.n_OnViewAttachedToWindow_Landroid_view_View_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_attachedView) [0x00011] in <d3b924763d4a465c85b26f6e8edc8a53>:0
  at at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.41(intptr,intptr,intptr)
  at java.lang.NoSuchMethodError: no static method "Lcom/xamarin/forms/platform/android/FormsViewGroup;.sendViewBatchUpdate(Landroid/view/View;FFIZFFFFFFFF)V
  at at crc643f46942d9dd1fff9.VisualElementTracker_AttachTracker.n_onViewAttachedToWindow(Native Method)
  at at crc643f46942d9dd1fff9.VisualElementTracker_AttachTracker.onViewAttachedToWindow(:31)
  at at android.view.View.dispatchAttachedToWindow(View.java:20116)
  at at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
  at at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
  at at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
  at at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
  at at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
  at at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
  at at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
  at at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
  at at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
  at at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2052)
  at at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
  at at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
  at at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
  at at android.view.Choreographer.doCallbacks(Choreographer.java:791)
  at at android.view.Choreographer.doFrame(Choreographer.java:726)
  at at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
  at at android.os.Handler.handleCallback(Handler.java:883)
  at at android.os.Handler.dispatchMessage(Handler.java:100)
  at at android.os.Looper.loop(Looper.java:214)
  at at android.app.ActivityThread.main(ActivityThread.java:7356)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by baruchn** [comment]
Turns out that `R8` is removing this method for some reason.
Adding the following `Proguard` rule fixed the issue:

```
-keep class com.xamarin.forms.platform.android.** {*;}
```

**Comment by PureWeen** [comment]
@baruchn can you attach a repro? I was trying to reproduce your issue and found some other issues linked here (https://github.com/xamarin/AndroidX/issues/83) but I couldn't reproduce your particular one

**Comment by samhouts** [comment]
@baruchn Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
