### PR TITLE
[UWP] Fixed inconsistency on UWP's DatePicker and the other OS's.

### PR DESCRIPTION
**Pull request by BradChase2011**
### Description of Change ###

Changed the DateTimeOffset on DatePickerRenderer.UWP to create a new date based on an unspecified time zone.

### Bugs Fixed ###

https://bugzilla.xamarin.com/show_bug.cgi?id=60001

### API Changes ###

None.

### Behavioral Changes ###

The DatePicker on UWP should show the same value as the other OS's.  There may be other ways to fix this issue, maybe changing the other OS's to match UWP?  Or another way to reset the DateTimeKind.  This worked for us in a jiffy.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by samhouts** [comment]
Did you happen to test this with alternate calendars? Thanks!

**Comment by BradChase2011** [comment]
@samhouts what do ya mean by alternate calendars?  I tested it with swapping out the datepicker with a calendar picker and with our custom uwp datepicker.  As far as timezones, this happens when the additional offset passes over the 12am barrier.  Hope that helps?

**Comment by samhouts** [comment]
I mean Hijri, Hebrew, etc. Regional alternate calendars. Not to worry, I will test them. Thanks!

**Comment by BradChase2011** [comment]
@samhouts I unfortunately did not :(.

**Comment by BradChase2011** [comment]
@samhouts there may be other options to solve this issue...  I was hoping for a quick switch on the uwp control, but that does exist :(.  Don't be afraid to try and find another solution instead of this one, I just wanted to make sure the code was up that worked for us.

**Comment by rmarinho** [comment]
Hi @BradChase2011 can you please rebase?! 

Thanks

**Comment by BradChase2011** [comment]
@rmarinho Rebased...

**Comment by rmarinho** [comment]
Build is failing 

Xamarin.Forms.Platform.UAP\DatePickerRenderer.cs (152, 5)
Xamarin.Forms.Platform.UAP\DatePickerRenderer.cs(152,5): Error CS0103: The name 'mindate' does not exist in the current context
Xamarin.Forms.Platform.UAP\DatePickerRenderer.cs (152, 36)
Xamarin.Forms.Platform.UAP\DatePickerRenderer.cs(152,36): Error CS0103: The name 'mindate' does not exist in the current context
Xamarin.Forms.Platform.UAP\DatePickerRenderer.cs (153, 42)
Xamarin.Forms.Platform.UAP\DatePickerRenderer.cs(153,42): Error CS0103: The name 'mindate' does not exist in the current context

**Comment by BradChase2011** [comment]
@rmarinho Fixed, sorry appeared to be a bad merge on my part.
